/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AkunController;
import controller.BukuController;
import controller.PenulisController;
import controller.PenulisBukuController;
import controller.TransaksiBukuController;
import java.sql.Connection;

/**
 *
 * @author Dayinta Warih Wulandari
 */
public class AdminView extends javax.swing.JInternalFrame {

    private final AkunController akunController;
    private final BukuController bukuController;
    private final PenulisController penulisController;
    private final PenulisBukuController pbc;
    private final TransaksiBukuController tbc;
    private final ViewProccess viewProccess;
    private final String[] headerBuku = {"ID Buku", "Judul", "Tahun", "Status"};
    private final String[] headerPenulis = {"ID Penulis", "Penulis"};
    private final String[] headerAkun = {"ID Member", "Nama", "Alamat"};
    private final String[] headerDetailBuku = {"ID Buku", "ID Penulis", "Judul", "Penulis", "Status"};
    private final String[] headerTransBuku = {"ID Transaksi", "ID Akun", "Nama", "Judul", "Tgl Pinjam", "Tgl Kembali", "Status", "Terlambat", "Denda"};
    private final String[] categoriesAkun;
    private final String[] categoriesBuku;
    private final String[] categoriesPenulis;
    private final String[] categoriesDetailBuku;
    private final String[] categoriesTransBuku;

    /**
     * Creates new form AdminView
     */
    public AdminView(Connection connection) {
        this.categoriesAkun = new String[]{"id", "nama", "alamat"};
        this.categoriesBuku = new String[]{"id", "judul", "tahun", "status"};
        this.categoriesPenulis = new String[]{"id", "penulis"};
        this.categoriesDetailBuku = new String[]{"buku_id", "penulis_id", "judul", "penulis", "status"};
        this.categoriesTransBuku = new String[]{"transaksi_id", "id", "nama", "judul", "Tgl tanggal_pinjam", "tanggal_kembali", "status", "terlambat", "denda"};
        initComponents();
        this.akunController = new AkunController(connection);
        this.bukuController = new BukuController(connection);
        this.penulisController = new PenulisController(connection);
        this.tbc = new TransaksiBukuController(connection);
        this.pbc = new PenulisBukuController(connection);
        this.viewProccess = new ViewProccess();
        //this.loadSearchComboBox();
        this.resetTrans();
        this.resetBuku();
        this.resetPenulis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdmin = new javax.swing.JTable();
        lblRole = new javax.swing.JLabel();
        btnTrans = new javax.swing.JButton();
        btnBuku = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnDetailBuku = new javax.swing.JButton();
        btnDetailMember = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        txtFind = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox();
        panelTrans = new javax.swing.JPanel();
        lblIdTrans = new javax.swing.JLabel();
        lbtTP = new javax.swing.JLabel();
        lblTK = new javax.swing.JLabel();
        txtIdTrans = new javax.swing.JTextField();
        txtTP = new javax.swing.JTextField();
        txtTK = new javax.swing.JTextField();
        lblIDAkunTrans = new javax.swing.JLabel();
        txtIdMemberTrans = new javax.swing.JTextField();
        lblIdBuku = new javax.swing.JLabel();
        txtIdBukuTrans = new javax.swing.JTextField();
        btnSaveTrans = new javax.swing.JButton();
        panelBuku = new javax.swing.JPanel();
        lblIdBukuInsertBuku = new javax.swing.JLabel();
        lblJudulBuku = new javax.swing.JLabel();
        lblTahunBuku = new javax.swing.JLabel();
        lblPenulisInsertBuku = new javax.swing.JLabel();
        cmbPenulis = new javax.swing.JComboBox();
        txtIdBukuInsert = new javax.swing.JTextField();
        txtJudulInsert = new javax.swing.JTextField();
        txtTahunInsert = new javax.swing.JTextField();
        btnSaveBuku = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdPenulisInsert = new javax.swing.JTextField();
        txtPenulisInsert = new javax.swing.JTextField();
        btnSavePenulis = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblWaktu = new javax.swing.JLabel();
        lblDenda = new javax.swing.JLabel();
        txtWaktu = new javax.swing.JTextField();
        txtDenda = new javax.swing.JTextField();
        btnSaveDenda = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Admin");
        setVisible(true);

        tblAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblAdmin);

        lblRole.setText("jLabel1");

        btnTrans.setText("Transaksi");
        btnTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransActionPerformed(evt);
            }
        });

        btnBuku.setText("Tambah Buku");
        btnBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukuActionPerformed(evt);
            }
        });

        jButton1.setText("Tambah Penulis");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnDetailBuku.setText("Detail Buku");
        btnDetailBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailBukuActionPerformed(evt);
            }
        });

        btnDetailMember.setText("Detail Member");
        btnDetailMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailMemberActionPerformed(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryActionPerformed(evt);
            }
        });

        panelTrans.setBorder(javax.swing.BorderFactory.createTitledBorder("Transaksi"));

        lblIdTrans.setText("ID Transaksi");

        lbtTP.setText("Tanggal Pinjam");

        lblTK.setText("Tanggal Kembali");

        lblIDAkunTrans.setText("ID Member");

        lblIdBuku.setText("ID Buku");

        btnSaveTrans.setText("Save");

        javax.swing.GroupLayout panelTransLayout = new javax.swing.GroupLayout(panelTrans);
        panelTrans.setLayout(panelTransLayout);
        panelTransLayout.setHorizontalGroup(
            panelTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTransLayout.createSequentialGroup()
                        .addGroup(panelTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIdTrans, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIDAkunTrans, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdBuku, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbtTP, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelTransLayout.createSequentialGroup()
                        .addComponent(lblTK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransLayout.createSequentialGroup()
                        .addGroup(panelTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIdBukuTrans, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(txtIdMemberTrans, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdTrans, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelTransLayout.createSequentialGroup()
                        .addGroup(panelTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTK, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(txtTP))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSaveTrans)
                .addContainerGap())
        );
        panelTransLayout.setVerticalGroup(
            panelTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdTrans)
                    .addComponent(txtIdTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDAkunTrans)
                    .addComponent(txtIdMemberTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdBuku)
                    .addComponent(txtIdBukuTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtTP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTransLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTK))
                .addGap(18, 18, 18)
                .addComponent(btnSaveTrans)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBuku.setBorder(javax.swing.BorderFactory.createTitledBorder("Buku"));

        lblIdBukuInsertBuku.setText("ID Buku");

        lblJudulBuku.setText("Judul");

        lblTahunBuku.setText("Tahun");

        lblPenulisInsertBuku.setText("Penulis");

        txtTahunInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTahunInsertActionPerformed(evt);
            }
        });

        btnSaveBuku.setText("Save");

        javax.swing.GroupLayout panelBukuLayout = new javax.swing.GroupLayout(panelBuku);
        panelBuku.setLayout(panelBukuLayout);
        panelBukuLayout.setHorizontalGroup(
            panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBukuLayout.createSequentialGroup()
                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBukuLayout.createSequentialGroup()
                                .addComponent(lblJudulBuku)
                                .addGap(37, 37, 37)
                                .addComponent(txtJudulInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBukuLayout.createSequentialGroup()
                                .addComponent(lblIdBukuInsertBuku)
                                .addGap(25, 25, 25)
                                .addComponent(txtIdBukuInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(panelBukuLayout.createSequentialGroup()
                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTahunBuku)
                            .addComponent(lblPenulisInsertBuku))
                        .addGap(29, 29, 29)
                        .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPenulis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTahunInsert))))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBukuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSaveBuku)
                .addContainerGap())
        );
        panelBukuLayout.setVerticalGroup(
            panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdBukuInsertBuku)
                    .addComponent(txtIdBukuInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJudulBuku)
                    .addComponent(txtJudulInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTahunBuku)
                    .addComponent(txtTahunInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPenulisInsertBuku)
                    .addComponent(cmbPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveBuku)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Penulis"));

        jLabel1.setText("ID Penulis");

        jLabel2.setText("Penulis");

        btnSavePenulis.setText("Save");
        btnSavePenulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePenulisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtPenulisInsert))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtIdPenulisInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 131, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSavePenulis)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPenulisInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPenulisInsert))
                .addGap(18, 18, 18)
                .addComponent(btnSavePenulis, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Denda"));

        lblWaktu.setText("Waktu");

        lblDenda.setText("Denda");

        btnSaveDenda.setText("Save");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSaveDenda))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWaktu)
                            .addComponent(lblDenda))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 123, Short.MAX_VALUE))
                            .addComponent(txtDenda))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWaktu)
                    .addComponent(txtWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDenda)
                    .addComponent(txtDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaveDenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFind))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelTrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDetailBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDetailMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuku)
                        .addGap(18, 18, 18)
                        .addComponent(btnDetailBuku)
                        .addGap(18, 18, 18)
                        .addComponent(btnTrans)
                        .addGap(20, 20, 20)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btnDetailMember)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTrans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukuActionPerformed
        txtIdBukuInsert.setEnabled(true);
        txtJudulInsert.setEnabled(true);
        txtTahunInsert.setEnabled(true);
        cmbPenulis.setEnabled(true);
        btnSaveBuku.setEnabled(true);
        bindingTableBuku();
        resetTrans();
        resetPenulis();
    }//GEN-LAST:event_btnBukuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtIdPenulisInsert.setEnabled(true);
        txtPenulisInsert.setEnabled(true);
        btnSavePenulis.setEnabled(true);
        bindingTablePenulis();
        resetBuku();
        resetTrans();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDetailMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailMemberActionPerformed
        bindingTableMember();
    }//GEN-LAST:event_btnDetailMemberActionPerformed

    private void btnDetailBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailBukuActionPerformed
        resetTrans();
        resetBuku();
        resetPenulis();
        bindingTableDetailBuku();
    }//GEN-LAST:event_btnDetailBukuActionPerformed

    private void btnTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransActionPerformed
        txtIdTrans.setEnabled(true);
        txtIdBukuTrans.setEnabled(true);
        txtIdMemberTrans.setEnabled(true);
        txtTK.setEnabled(true);
        txtTP.setEnabled(true);
        btnSaveTrans.setEnabled(true);
        bindingTableTransBuku();
        resetBuku();
        resetPenulis();
    }//GEN-LAST:event_btnTransActionPerformed

    private void btnSavePenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSavePenulisActionPerformed

    private void txtTahunInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTahunInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTahunInsertActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindActionPerformed

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuku;
    private javax.swing.JButton btnDetailBuku;
    private javax.swing.JButton btnDetailMember;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnSaveBuku;
    private javax.swing.JButton btnSaveDenda;
    private javax.swing.JButton btnSavePenulis;
    private javax.swing.JButton btnSaveTrans;
    private javax.swing.JButton btnTrans;
    private javax.swing.JComboBox cmbCategory;
    private javax.swing.JComboBox cmbPenulis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDenda;
    private javax.swing.JLabel lblIDAkunTrans;
    private javax.swing.JLabel lblIdBuku;
    private javax.swing.JLabel lblIdBukuInsertBuku;
    private javax.swing.JLabel lblIdTrans;
    private javax.swing.JLabel lblJudulBuku;
    private javax.swing.JLabel lblPenulisInsertBuku;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTK;
    private javax.swing.JLabel lblTahunBuku;
    private javax.swing.JLabel lblWaktu;
    private javax.swing.JLabel lbtTP;
    private javax.swing.JPanel panelBuku;
    private javax.swing.JPanel panelTrans;
    private javax.swing.JTable tblAdmin;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtIdBukuInsert;
    private javax.swing.JTextField txtIdBukuTrans;
    private javax.swing.JTextField txtIdMemberTrans;
    private javax.swing.JTextField txtIdPenulisInsert;
    private javax.swing.JTextField txtIdTrans;
    private javax.swing.JTextField txtJudulInsert;
    private javax.swing.JTextField txtPenulisInsert;
    private javax.swing.JTextField txtTK;
    private javax.swing.JTextField txtTP;
    private javax.swing.JTextField txtTahunInsert;
    private javax.swing.JTextField txtWaktu;
    // End of variables declaration//GEN-END:variables

    public void bindingTableBuku() {
        this.viewProccess.loadData(this, tblAdmin, headerBuku,
                this.bukuController.bindingSort(categoriesBuku[0], "asc"));
    }

    public void bindingTablePenulis() {
        this.viewProccess.loadData(this, tblAdmin, headerPenulis,
                this.penulisController.bindingSort(categoriesPenulis[0], "asc"));
    }

    public void bindingTableMember() {
        String idmember = "2";
        this.viewProccess.loadData(this, tblAdmin, headerAkun,
                this.akunController.find(categoriesAkun[0], idmember));
    }

    public void bindingTableDetailBuku() {
        this.viewProccess.loadData(this, tblAdmin, headerDetailBuku,
                this.pbc.bindingSort(categoriesDetailBuku[0], "asc"));
    }

    public void bindingTableTransBuku() {
        this.viewProccess.loadData(this, tblAdmin, headerTransBuku,
                this.tbc.bindingSort(categoriesTransBuku[0], "asc"));
    }

    public void resetTrans() {
        //Transaksi
        txtIdTrans.setEnabled(false);
        txtIdBukuTrans.setEnabled(false);
        txtIdMemberTrans.setEnabled(false);
        txtTK.setEnabled(false);
        txtTP.setEnabled(false);
        btnSaveTrans.setEnabled(false);
    }

    //Buku
    public void resetBuku() {
        txtIdBukuInsert.setEnabled(false);
        txtJudulInsert.setEnabled(false);
        txtTahunInsert.setEnabled(false);
        cmbPenulis.setEnabled(false);
        btnSaveBuku.setEnabled(false);
    }

    public void resetPenulis() {
        txtIdPenulisInsert.setEnabled(false);
        txtPenulisInsert.setEnabled(false);
        btnSavePenulis.setEnabled(false);
        
    }
    
        public void saveOrEditPenulis(String id, String penulis, boolean isSave) {
        boolean flag = false;
        if (isSave) {
            flag = this.penulisController.save(id,penulis);
        } else {
            flag = this.penulisController.edit(id, penulis);
        }
        this.viewProccess.saveData(this, flag, isSave);
        this.resetPenulis();
    }
    
//    public void resetDenda(){
//        txtWaktu.setEnabled(false);
//        txtDenda.setEnabled(false);
//        btnSaveDenda.setEnabled(false);
//    }

//        txtId.setEditable(false);
//        txtId.setText(this.regionController.getAutoId());
//        txtName.setText("");
//        txtSearch.setText("");
//        this.bindingTable();
//        btnDrop.setEnabled(false);
}
